# Generated by Django 2.1.4 on 2019-05-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pokeruser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokeruser',
            name='balance',
            field=models.CharField(default='200', max_length=100),
            preserve_default=False,
        ),
    ]
